project_id = "paywwbuqycovjopryele"

[functions]
[functions.admin-upload-worker-photo]
verify_jwt = true

[functions.new-booking-telegram]
verify_jwt = false

[functions.scheduled-dispatch]
verify_jwt = false

[functions.create-rtc-call]
verify_jwt = true

[functions.accept-rtc-call]
verify_jwt = true

[functions.end-rtc-call]
verify_jwt = true
