import type { Recipe } from "./types";

// Seed recipes shown while the external `recipes` table is empty or unreachable.
// The image URLs point to CDN-hosted assets uploaded via lovable-assets.
export const SEED_RECIPES: Recipe[] = [
  {
    id: "seed-upma",
    slug: "upma",
    name: "Upma",
    image_url: "/__l5e/assets-v1/2f6223f4-baaf-4295-9761-698b5386d5e1/upma.jpg",
    cooking_time_min: 20,
    difficulty: "easy",
    diet: "veg",
    categories: ["breakfast", "quick"],
    calories: 280,
    serves: 2,
  },
  {
    id: "seed-dosa",
    slug: "masala-dosa",
    name: "Masala Dosa",
    image_url: "/__l5e/assets-v1/11bc31fc-d359-40fc-8ee0-daa63b47b2fd/dosa.jpg",
    cooking_time_min: 35,
    difficulty: "medium",
    diet: "veg",
    categories: ["breakfast", "dinner"],
    calories: 420,
    serves: 2,
  },
  {
    id: "seed-poha",
    slug: "poha",
    name: "Poha",
    image_url: "/__l5e/assets-v1/16da0e18-c6d3-45b1-9cb1-4f2ed305b8ca/poha.jpg",
    cooking_time_min: 15,
    difficulty: "easy",
    diet: "veg",
    categories: ["breakfast", "quick", "healthy"],
    calories: 250,
    serves: 2,
  },
  {
    id: "seed-idli",
    slug: "idli",
    name: "Idli",
    image_url: "/__l5e/assets-v1/e107bb9f-70e6-46b0-855f-bb1d0c354b33/idli.jpg",
    cooking_time_min: 25,
    difficulty: "easy",
    diet: "veg",
    categories: ["breakfast", "healthy", "kids"],
    calories: 210,
    serves: 3,
  },
  {
    id: "seed-tomato-rice",
    slug: "tomato-rice",
    name: "Tomato Rice",
    image_url: "/__l5e/assets-v1/1e292c44-56c1-426d-983d-3e3a95333462/tomato-rice.jpg",
    cooking_time_min: 30,
    difficulty: "easy",
    diet: "veg",
    categories: ["lunch", "dinner"],
    calories: 380,
    serves: 3,
  },
  {
    id: "seed-paneer-butter-masala",
    slug: "paneer-butter-masala",
    name: "Paneer Butter Masala",
    image_url: "/__l5e/assets-v1/8541b876-2bb2-4364-8541-14b8ab369b89/paneer-butter-masala.jpg",
    cooking_time_min: 40,
    difficulty: "medium",
    diet: "veg",
    categories: ["lunch", "dinner"],
    calories: 520,
    serves: 3,
  },
  {
    id: "seed-dal-tadka",
    slug: "dal-tadka",
    name: "Dal Tadka",
    image_url: "/__l5e/assets-v1/3132383f-8e1d-4814-b745-0ceadeeebb9e/dal-tadka.jpg",
    cooking_time_min: 30,
    difficulty: "easy",
    diet: "veg",
    categories: ["lunch", "dinner", "healthy"],
    calories: 220,
    serves: 3,
  },
  {
    id: "seed-chicken-curry",
    slug: "chicken-curry",
    name: "Chicken Curry",
    image_url: "/__l5e/assets-v1/c4621ada-dfa6-4912-aba4-f7a1c803cd32/chicken-curry.jpg",
    cooking_time_min: 45,
    difficulty: "medium",
    diet: "non_veg",
    categories: ["lunch", "dinner"],
    calories: 480,
    serves: 3,
  },
  {
    id: "seed-egg-curry",
    slug: "egg-curry",
    name: "Egg Curry",
    image_url: "/__l5e/assets-v1/c7a1a17e-0b62-48f6-b3fa-50f95410d4b2/egg-curry.jpg",
    cooking_time_min: 30,
    difficulty: "easy",
    diet: "egg",
    categories: ["lunch", "dinner"],
    calories: 320,
    serves: 3,
  },
  {
    id: "seed-jeera-rice",
    slug: "jeera-rice",
    name: "Jeera Rice",
    image_url: "/__l5e/assets-v1/0d79bd76-8315-446e-a4e0-1968acbf3353/jeera-rice.jpg",
    cooking_time_min: 20,
    difficulty: "easy",
    diet: "veg",
    categories: ["lunch", "dinner", "quick"],
    calories: 300,
    serves: 3,
  },
  {
    id: "seed-veg-pulao",
    slug: "veg-pulao",
    name: "Veg Pulao",
    image_url: "/__l5e/assets-v1/2cda4b4e-3e18-4091-8b60-5a648fc7600e/veg-pulao.jpg",
    cooking_time_min: 35,
    difficulty: "medium",
    diet: "veg",
    categories: ["lunch", "dinner"],
    calories: 400,
    serves: 4,
  },
  {
    id: "seed-fried-rice",
    slug: "fried-rice",
    name: "Veg Fried Rice",
    image_url: "/__l5e/assets-v1/b10d8cd2-5d7f-40ae-abc5-7b2bae681c8c/fried-rice.jpg",
    cooking_time_min: 20,
    difficulty: "easy",
    diet: "veg",
    categories: ["lunch", "dinner", "kids", "quick"],
    calories: 360,
    serves: 3,
  },
];
