// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { auth as firebaseAuth } from '@/lib/firebase';

const SUPABASE_URL = "https://paywwbuqycovjopryele.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBheXd3YnVxeWNvdmpvcHJ5ZWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjkyNjksImV4cCI6MjA3MDc0NTI2OX0.js1MaTBkjuGlaDfQjrZpZ9_G8Jy9ygNAB8KpNDiQg8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  accessToken: async () => {
    const user = firebaseAuth.currentUser;
    if (!user) {
      console.log("[Supabase] No Firebase user, returning null token");
      return null;
    }
    try {
      const token = await user.getIdToken(false);
      console.log("[Supabase] Got Firebase ID token for user:", user.uid);
      return token;
    } catch (e) {
      console.error("[Supabase] Failed to get Firebase ID token:", e);
      return null;
    }
  },
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
});
